TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.3
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.3
  backup_vel: -0.2
  escape_vel: -0.2
  acc_lim_theta: 0.8
  acc_lim_x: 0.4
  acc_lim_y: 0.4
  holonomic_robot: false    #我们的机器人没有y方向速度，所以不完整
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  meter_scoring: true

  
  
