# 全局点云地图转gridmap的设置参数
pcl_grid_map_extraction:
  num_processing_threads: 4
  cloud_transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation: #intrinsic rotation X-Y-Z (r-p-y)sequence
      r: 0.0
      p: 0.0
      y: 0.0
  cluster_extraction:
    cluster_tolerance: 0.25
    min_num_points: 1
    max_num_points: 1000000
  outlier_removal:
    is_remove_outliers: true
    mean_K: 10   #越大越快
    stddev_threshold: 1.0
  downsampling:
    is_downsample_cloud: true
    voxel_size:
      x: 0.1 #0.02
      y: 0.1 #0.02
      z: 0.1 #0.02 
  grid_map:
    min_num_points_per_cell: 1 #4
    resolution: 0.15  # local_map的分辨率，需要和global_map同步。越大越快
