TrajectoryPlannerROS:
  max_vel_x: 1.0
  min_vel_x: 0.1
  max_vel_theta: 0.8 # 0.5
  min_vel_theta: -1.0 # 0.5
  min_in_place_vel_theta: 0.3 # 0.7
  acc_lim_theta: 0.8 # 1.0
  acc_lim_x: 0.6
  acc_lim_y: 0.6
  holonomic_robot: false
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.3
  meter_scoring: true

  sim_time: 3.0
  # pdist_scale: 0.6
  # gdist_scale: 3.0
  # publish_cost_grid_pc: true
  # prune_plan: false
  # daw: false
  
  
