global_costmap:

  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: true
  # rolling_window: true

  width: 100.0
  height: 100.0
  resolution: 0.15

  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    # - {name: gridlayer,        type: "simple_layer_namespace::GridLayer"}     
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}