# Parameter for mark_tracking.cpp

##降落追踪 的比例参数
kpx_land: 0.75
kpy_land: 0.75
kpz_land: 0.75

##降落追踪 的积分参数
kix_land: 0.085
kiy_land: 0.085
kiz_land: 0.085

##降落追踪 的微分参数
kdx_land: 0.0
kdy_land: 0.0
kdz_land: 0.0


##低高度时降落追踪 的比例参数
kpx_land2: 0.7
kpy_land2: 0.7
kpz_land2: 0.7

##低高度时降落追踪 的积分参数
#位姿转换前使用的参数
# kix_land2: 0.17
# kiy_land2: 0.17
# kiz_land2: 0.17

#位姿转换后使用的参数
kix_land2: 0.09
kiy_land2: 0.09
kiz_land2: 0.09

##低高度时降落追踪 的微分参数
# kdx_land2: 0.15
# kdy_land2: 0.15
# kdz_land2: 0.15

#位姿转换后使用的参数
kdx_land2: 0.09
kdy_land2: 0.09
kdz_land2: 0.09

##降落追踪控制算法的最大速度
Max_velx_land: 1
Max_vely_land: 1
Max_velz_land: 1

##降落追踪控制算法的速度死区
Thres_velx_land: 0.0
Thres_vely_land: 0.0
Thres_velz_land: 0.0

##允许降落最大距离阈值
Thres_distance_land: 0.1

##允许降落计数阈值
Thres_count_land: 2

##视觉丢失计数阈值
Thres_vision_lost: 15

##调整高度计数阈值
Thres_count_z: 20

##降落板的高度
mark_hight: 0

##允许降落最大高度阈值
land_max_z: 0.25

##允许飞行最低高度[这个高度是指降落板上方的相对高度]
fly_min_z: 0.2

##允许飞行最大高度[这个高度是指降落板上方的相对高度]
fly_max_z: 4

##起飞高度
takeoff_hgt: 4

##相机参数(视角为100°，1280*720)
fx: 200.0
fy: 200.0
cx: 640.0
cy: 360.0

##畸变参数
k1: 0.0007689952035434544
k2: 0.030314499512314796
p1: -0.028857899829745293
p2: 0.0037220960948616266
k3: 0.0

#**************************地标识别有关***************************
# 地标类型 0-H型地标 1-X型地标 2-字母地标 3-数字地标 9-未指定
Mark_type: 3
