grid_map_topic: /grid_map_resolution_change_demo/grid_map
grid_map_visualizations:
  - name: occupancy_grid
    type: occupancy_grid
    params:
     layer: elevation
     data_min: 0.0
     data_max: 0.3