#rover: #spx: 不要用绝对路径！
  # Publish the joint states to joint_states. 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  left_front_axle_ctrlr:
    type: effort_controllers/JointVelocityController
    joint: front_left_wheel_joint
    pid: {p: 500, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_front_axle_ctrlr:
    type: effort_controllers/JointVelocityController
    joint: front_right_wheel_joint
    pid: {p: 500, i: 0.0, d: 0.0, i_clamp: 0.0}
  left_rear_axle_ctrlr:
    type: effort_controllers/JointVelocityController
    joint: rear_left_wheel_joint
    pid: {p: 500, i: 0.0, d: 0.0, i_clamp: 0.0}
  right_rear_axle_ctrlr:
    type: effort_controllers/JointVelocityController
    joint: rear_right_wheel_joint
    pid: {p: 500, i: 0.0, d: 0.0, i_clamp: 0.0}


  left_steering_ctrlr:
    joint: front_left_steering_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1000.0, i: 0.0, d: 100}
  right_steering_ctrlr:
    joint: front_right_steering_joint
    type: effort_controllers/JointPositionController
    pid: {p: 1000.0, i: 0.0, d: 100}
