left_front_wheel:
  steering_link_name: front_left_wheel
  steering_controller_name: left_steering_ctrlr
  axle_controller_name: left_front_axle_ctrlr
  diameter: 0.635

right_front_wheel:
  steering_link_name: front_right_wheel
  steering_controller_name: right_steering_ctrlr
  axle_controller_name: right_front_axle_ctrlr
  diameter: 0.635

left_rear_wheel:
  link_name: rear_left_wheel
  axle_controller_name: left_rear_axle_ctrlr
  diameter: 0.635

right_rear_wheel:
  link_name: rear_right_wheel
  axle_controller_name: right_rear_axle_ctrlr
  diameter: 0.635