depth_to_gridmap:
  image_topic: "/kinect/depth/image_raw"
  resolution: 0.3
  map_frame_id: "map"
  min_height: 0.0
  max_height: 10.0

grid_map_visualization:
  grid_map_topic: /depth_to_gridmap/grid_map
  grid_map_visualizations:
    - name: elevation_points
      type: point_cloud
      params:
        layer: elevation
    - name: elevation_grid
      type: occupancy_grid
      params:
        layer: elevation
        data_min: -0.2
        data_max: 0.2
    - name: flat_grid
      type: flat_point_cloud
      params:
        height: 0.0
